USE ERP_HOMOLOG;

SELECT * from ITEM

UPDATE ITEM
SET
    DESCRICAO = 'Updated Item Description',
    GRUPOITEM = 1,
    SUBGRUPOITEM = 1,
    TIPOVALIDADE = 1,
    VALIDADE = 1,
    TEMGARANTIA = 1,
    GARANTIA = 1,
    SITUACAO = 1,
    VALORUNITARIO = 1,
    DATAALTERACAO = GETDATE(),
    USUARIOALTERACAO = 1
WHERE ITEM = 1;